### ISSUE TITLE
proximity

### ISSUE THREAD

**Issue by zmjones** [zmjones/rfss#2]
the proximity matrix might be something that we should discuss and use in the example. if we mapped it over time or projected it using mds or something it could be interesting in discovering dependence (social/spatial/temporal) as well as outliers (observations not proximate to anything else). both of which would be useful for later modeling/theorizing.

**Comment by flinder** [comment]
Yeah now that we have more space for technical stuff.. We just have to be careful to not make it too long again :)

**Comment by zmjones** [comment]
yea agreed. since we are emphasizing that you can substantively interpret random forests i think this would be good, as it is quite different from what other models/algorithms use. do you know much about scaling?
